# Generated by Django 4.0.3 on 2022-07-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('category', models.CharField(choices=[('MIRACLE', 'MIRACLE'), ('HOMEWORK', 'HOMEWORK')], max_length=50)),
                ('goal', models.CharField(max_length=50, verbose_name='목표')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='알람 설정')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=100, verbose_name='요일')),
                ('routine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routine.routine', verbose_name='루틴')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
