# Generated by Django 4.0.3 on 2022-07-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_alter_routine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine', verbose_name='루틴'),
        ),
    ]
