# Generated by Django 4.0.3 on 2022-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routineday_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.CharField(choices=[('MIRACLE', 'MIRACLE'), ('HOMEWORK', 'HOMEWORK')], max_length=50, verbose_name='분류'),
        ),
    ]
