# Generated by Django 4.0.3 on 2022-07-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_alter_routine_created_at_alter_routineday_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
